<a href="https://colab.research.google.com/github/Anakha-200/-AI_ProblemSolving_RA2411026050004_RA2411026050007/blob/main/TEXT_INFORMATION_RETRIEVAL_USING_TF_IDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import nltk
import re
import math

In [2]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [3]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [4]:
documents=[ """In this paper, for Markov Decision Processes (MDPs) with standard Borel spaces, (i) we first provide a discretization based approximation method for MDPs with continuous spaces under average
cost criteria, and provide error bounds for approximations when the dynamics are only weakly continuous (for asymptotic convergence of errors as the grid sizes vanish) or Wasserstein continuous
(with a rate in approximation as the grid sizes vanish) under certain ergodicity assumptions. In
particular, we relax the total variation condition given in prior work to weak continuity or Wasserstein continuity. (ii) We provide synchronous and asynchronous (quantized) Q-learning algorithms
for continuous spaces via quantization (where the quantized state is taken to be the actual state
in corresponding Q-learning algorithms presented in the paper), and establish their convergence.
(iii) We finally show that the convergence is to the optimal Q values of a finite approximate model
constructed via quantization, which implies near optimality of the arrived solution.
Keywords: Reinforcement learning, stochastic control, finite approximations, MDPs with general
spaces""", """Finding efficient solutions to MDPs with continuous spaces is a challenging and important problem. In this context, various approximation techniques have been presented (see e.g. Dufour and
Prieto-Rumeau, 2012; Bertsekas, 1975; Chow and Tsitsiklis, 1991; Bertsekas and Tsitsiklis, 1996a;
Szepesvari, 2010; Tsitsiklis and Roy, 1997; Singh et al., 1995; Melo et al., 2008; Gaskett and ´
D. Wettergreen, 1999; Szepesvari and Smart, 2004; Meyn, 2022; Saldi et al., 2017, 2018). Many `
studies in the literature have focused on either finite-horizon problems or infinite-horizon discounted
cost problems, using the dynamic programming principle and the contraction properties of Bellman
operators induced by the discount factor. For average cost problems, however, the same techniques
are not immediately applicable.
For MDPs with continuous state spaces, existence of optimal solutions has been well studied
under the infinite horizon average cost criterion, under either weak continuity of the kernel (in both
state and action) or strong continuity (of the kernel in actions for every state), together with various
stability/ergodicity assumptions. We refer the reader to the works by Arapostathis et al. (1993);
Hernandez-Lerma (2012); Hern ´ andez-Lerma and Lasserre (1996, 1999); Costa and Dufour (2012); ´
Gordienko and Hernandez-Lerma (1995); Vega-Amaya (2003a,b); Hern ´ andez-Lerma and Lasserre ´
(1996); Borkar (2001); Feinberg et al. (2012) for comprehensive surveys on optimality results and
general solution techniques for optimal control under the average cost criteria. However, research
on computational and reinforcement learning methods for average cost optimality still entails open
problems, especially for MDPs with continuous spaces.
The primary contributions of the paper concern finite approximations for MDPs with continuous spaces, their near optimality, and reinforcement learning for average cost problems. We will
summarize the related research in these areas separately:
Approximations for MDPs with continuous spaces. For the study of continuous space MDPs,
establishing regularity and continuity properties of the value functions is crucial. To this end, one
usually needs continuity assumptions on the stage-wise cost functions, and continuity assumptions
on the transition models under a suitable metric. Weak convergence metrics, and Wasserstein distances are used frequently for the regularity of the transition models since they are, in general""", """weaker and less demanding than other metric choices, e.g., total variation and relative entropy
(Kullback–Leibler divergence) type distance notions. These are used to establish Lipschitz continuity of the value functions, as well as to establish the consistency of model approximations. The
papers by Pirotta et al. (2015); Asadi et al. (2018); Rachelson and Lagoudakis (2010); Maran et al.
(2023) study MDPs with Wasserstein continuous transition models under the discounted cost setting. However, one drawback of these papers is that they work on a class of Lipschitz continuous
policies which is a suboptimal class in general. For the discounted cost criterion, Saldi et al. (2016,
2015a,b, 2017); Kara et al. (2023) have shown that under only weak continuity conditions for an
MDP with standard Borel state and action spaces, finite models obtained by the quantization of the
state and action spaces lead to control policies that are asymptotically optimal as the quantization
rate increases. They also established convergence rates under Lipschitz continuity assumptions on
the model, without requiring the class of policies to be a priori continuous. The authors of the current paper generalized these results to general approximation schemes beyond discretization based
approaches under several different continuity assumptions on the transition models such as continuous weak continuity, set-wise continuity as well as total variation continuity (Kara and Yuksel, ¨
2020, 2021).
On the weak metrics for approximations and robustness to model mismatch. Related to the
discussion above, a salient consideration involving approximations for MDPs with general spaces
is that unless convergence in models occurs in a strong sense, such as in total variation uniform over
sets and actions, as models approach one another, the induced expected costs may not asymptotically
agree under every admissible policy. If convergence is to hold under the Wasserstein metric, such
a uniform convergence only would hold if policies were restricted to be Lipschitz a priori (see e.g.
Pirotta et al., 2015; Asadi et al., 2018; Rachelson and Lagoudakis, 2010; Maran et al., 2023), which
is often too restrictive for the approximate models. A detailed study on such model convergence and
robustness has been carried out by Kara and Yuksel (2020, 2021).""", """Under ¨ continuous convergence
of kernels, Kara and Yuksel (2020) in discrete-time and Pradhan and Y ¨ uksel (2024) in continuous- ¨
time, established robustness when a control policy designed for an approximate/incorrect model is
applied to a true model. Saldi et al. (2017); Kara and Yuksel (2021); Kara et al. (2023) present ¨
a construction for the approximate models through quantizing the actual model with continuous
spaces, which allows for continuity and robustness results with only a weak continuity assumption
on the true transition kernel which, in turn, leads to continuous weak convergence of approximate
models as discussed by Kara and Yuksel (2021) and thus becomes an important special case of ¨
robustness under model convergence. Closely related to such results and continuous convergence,
a topology on spaces of probability measures corresponding to laws of stochastic processes, which
has been used in a wide variety of contexts in stochastic analysis, is defined as follows: a sequence
of stochastic processes is said to converge to another process if their finite-dimensional marginals
converge weakly, and their conditional distributions of future variables given the past (viewed as
measure-valued stochastic processes) also converge weakly. Aldous (1981) has termed this extended
weak convergence and Hellwig (1996) has named it the information topology; these have recently
been shown to be equivalent in discrete-time by Backhoff-Veraguas et al. (2020a); Pammer (2024).
The adapted Wasserstein metric (see Bartl et al., 2024; Backhoff-Veraguas et al., 2020a; Beiglbock ¨
et al., 2022) has been shown to possess similar robustness properties in a variety of applications
(Bayraktar et al., 2020; Backhoff-Veraguas et al., 2020b; Bartl and Wiesel, 2023), not unlike the
continuous weak convergence notion noted above (see Saldi and Yuksel (2025) for a comprehensive ¨
review). Please see Section 3.2.1 for further discussion.
""", """Approximations for the average cost criterion. We note that the analysis of average cost problems
is typically more challenging, especially for problems with continuous spaces, as the stability (or
the ergodicity) of the problem plays a crucial role. For the average cost criterion, Saldi (2019), Saldi
et al. (2018, Theorem 4.14) provide error bounds for finite approximations; however, these results
require total variation continuity of the transition models as well as certain mixing conditions.
In this paper, we relax the total variation continuity condition to weak or Wasserstein continuity.
Reinforcement learning for the average cost criterion. There are a number of publications that
study reinforcement learning methods for MDPs under average cost criterion. To our knowledge,
the majority of these studies focus on finite spaces.
The papers by Abounadi et al. (2001); Gosavi (2004) are among the earliest studies that provide
convergent learning algorithms based on relative value iteration (as well as stochastic shortest path
under a recurrence condition for a given state), and the convergence of these algorithms has been
established via the ODE method by Borkar and Meyn (2000) for finite models.
Konda and Tsitsiklis (2003) studied policy improvement and actor-critic methods for continuous
space (in particular, Polish space) MDPs under average cost criteria. The approach relies on the
linear approximation of the value functions and the parametrization of the policies. The convergence
of this method is shown under a uniform minorization assumption over the parametrized policy
space (Konda and Tsitsiklis, 2003, Assumption 4.2) which is similar to the assumption used in our
paper (see Assumption 1). However, the learned solution is only locally optimal due to the nature
of policy parametrization methods."""
]

In [5]:
df = pd.DataFrame({
    "Document_ID": [f"D{i+1}" for i in range(len(documents))],
    "Text": documents
})

df

  Document_ID                                               Text
0          D1  In this paper, for Markov Decision Processes (...
1          D2  Finding efficient solutions to MDPs with conti...
2          D3  weaker and less demanding than other metric ch...
3          D4  Under ¨ continuous convergence\nof kernels, Ka...
4          D5  Approximations for the average cost criterion....

In [6]:
def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]
    return words

In [7]:
df["Processed_Text"] = df["Text"].apply(preprocess)

df[["Document_ID", "Processed_Text"]]

  Document_ID                                     Processed_Text
0          D1  [paper, markov, decision, process, mdps, stand...
1          D2  [finding, efficient, solution, mdps, continuou...
2          D3  [weaker, less, demanding, metric, choice, eg, ...
3          D4  [continuous, convergence, kernel, kara, yuksel...
4          D5  [approximation, average, cost, criterion, note...

In [8]:
vocabulary = sorted(
    set(word for doc in df["Processed_Text"] for word in doc)
)

print("Vocabulary Size:", len(vocabulary))

Vocabulary Size: 347

In [9]:
def calculate_tf(document):
    tf = {}
    total_words = len(document)

    for word in vocabulary:
        tf[word] = document.count(word) / total_words

    return tf

In [10]:
tf_matrix = []

for doc in df["Processed_Text"]:
    tf_matrix.append(calculate_tf(doc))

tf_df = pd.DataFrame(tf_matrix, index=df["Document_ID"])

tf_df.round(4)

,ab,abounadi,action,actorcritic,actual,adapted,admissible,agree,al,aldous,...,weaker,weakly,well,wettergreen,wide,wiesel,without,work,would,yuksel
Document_ID,,,,,,,,,,,,,,,,,,,,,
D1,0.0000,0.0000,0.0000,0.0000,0.0094,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0094,0.0000,0.0000,0.0000,0.0000,0.0000,0.0094,0.0000,0.0000
D2,0.0047,0.0000,0.0093,0.0000,0.0000,0.0000,0.0000,0.0000,0.0234,0.0000,...,0.0000,0.0000,0.0047,0.0047,0.0000,0.0000,0.0000,0.0047,0.0000,0.0000
D3,0.0047,0.0000,0.0141,0.0000,0.0000,0.0000,0.0047,0.0047,0.0376,0.0000,...,0.0047,0.0000,0.0094,0.0000,0.0000,0.0000,0.0047,0.0047,0.0047,0.0094
D4,0.0000,0.0000,0.0000,0.0000,0.0058,0.0058,0.0000,0.0000,0.0468,0.0058,...,0.0000,0.0117,0.0000,0.0000,0.0058,0.0058,0.0000,0.0000,0.0000,0.0234
D5,0.0000,0.0062,0.0000,0.0062,0.0000,0.0000,0.0000,0.0000,0.0123,0.0000,...,0.0000,0.0000,0.0123,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [11]:
N = len(df)

idf = {}

for word in vocabulary:
    df_count = sum(1 for doc in df["Processed_Text"] if word in doc)
    idf[word] = math.log((N + 1) / (df_count + 1)) + 1

idf_df = pd.DataFrame(
    list(idf.items()),
    columns=["Term", "IDF"]
)

idf_df

            Term       IDF
0             ab  1.693147
1       abounadi  2.098612
2         action  1.693147
3    actorcritic  2.098612
4         actual  1.693147
..           ...       ...
342       wiesel  2.098612
343      without  2.098612
344         work  1.405465
345        would  2.098612
346       yuksel  1.693147

[347 rows x 2 columns]

In [12]:
tfidf_matrix = []

for doc in df["Processed_Text"]:
    tf = calculate_tf(doc)

    tfidf = {}

    for word in vocabulary:
        tfidf[word] = tf[word] * idf[word]

    tfidf_matrix.append(tfidf)

tfidf_df = pd.DataFrame(
    tfidf_matrix,
    index=df["Document_ID"]
)

tfidf_df.round(4)

,ab,abounadi,action,actorcritic,actual,adapted,admissible,agree,al,aldous,...,weaker,weakly,well,wettergreen,wide,wiesel,without,work,would,yuksel
Document_ID,,,,,,,,,,,,,,,,,,,,,
D1,0.0000,0.000,0.0000,0.000,0.0160,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0160,0.0000,0.0000,0.0000,0.0000,0.0000,0.0133,0.0000,0.0000
D2,0.0079,0.000,0.0158,0.000,0.0000,0.0000,0.0000,0.0000,0.0276,0.0000,...,0.0000,0.0000,0.0066,0.0098,0.0000,0.0000,0.0000,0.0066,0.0000,0.0000
D3,0.0079,0.000,0.0238,0.000,0.0000,0.0000,0.0099,0.0099,0.0444,0.0000,...,0.0099,0.0000,0.0132,0.0000,0.0000,0.0000,0.0099,0.0066,0.0099,0.0159
D4,0.0000,0.000,0.0000,0.000,0.0099,0.0123,0.0000,0.0000,0.0553,0.0123,...,0.0000,0.0198,0.0000,0.0000,0.0123,0.0123,0.0000,0.0000,0.0000,0.0396
D5,0.0000,0.013,0.0000,0.013,0.0000,0.0000,0.0000,0.0000,0.0146,0.0000,...,0.0000,0.0000,0.0174,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [13]:
query = input("Enter your query: ")

Enter your query: machine learning decision making

In [14]:
processed_query = preprocess(query)

query_terms = [word for word in processed_query if word in vocabulary]

print(query_terms)

['learning', 'decision']

In [15]:
scores = {}

for doc in tfidf_df.index:
    score = 0

    for term in query_terms:
        score += tfidf_df.loc[doc, term]

    scores[doc] = score

In [16]:
results = pd.DataFrame(
    list(scores.items()),
    columns=["Document_ID", "Score"]
)

results = results.sort_values(
    by="Score",
    ascending=False
)

print(results)

  Document_ID     Score
0          D1  0.033057
4          D5  0.026027
1          D2  0.013135
2          D3  0.000000
3          D4  0.000000

In [17]:
top_doc = results.iloc[0]["Document_ID"]

print("Most Relevant Document ID:", top_doc)

Most Relevant Document ID: D1